### ISSUE TITLE
QueueIds

### ISSUE THREAD

**Issue by Koboo** [luissilva1044894/hirez-api-docs#8]
Hello there,

I got a really "simple" question, but first of all: Thank you for your work on this documentation!

My question is: How do you map the gamemodes to their respective queue-ids? I couldn't find any documentation about them.

The reason for this is, I would dislike to depend on hoping that the documentation is up to date and would like to take action myself in case of emergency, as I would like to map the values hardcoded.

Best regards
Koboo

**Comment by luissilva1044894** [comment]
Hey, @Koboo! 

Well, it's not updated and unofficial... I'm being around nothing related to Hi-Rez. 

Maybe there is new Ids or some are removed. It's being a while since I checked it. And yep, it can be hardcoded, usually that don't change that much.
You can always check the **queue** in **API Parameter Details** on the [**official documentation**](https://docs.google.com/document/d/1OFS-3ocSx-1Rvg4afAnEHlT3917MAK_6eJTR6rzr-BM/edit#heading=h.mbb9ngfr6vgg)

![image](https://user-images.githubusercontent.com/26727089/197339997-f5d3ab6f-7100-44b8-8f71-6ac5bd1fd998.png)

**Comment by Koboo** [comment]
Thanks for the fast response!

That's exactly what I was looking for.

Have a great day!
